export enum ConversationState {

  IDLE = 'IDLE',

  GREETING = 'GREETING',

  WAITING_PRODUCT = 'WAITING_PRODUCT',

  WAITING_VEHICLE = 'WAITING_VEHICLE',

  WAITING_BRAND = 'WAITING_BRAND',

  SEARCHING = 'SEARCHING',

  TRANSFER_HUMAN = 'TRANSFER_HUMAN',

  FINISHED = 'FINISHED',

}
