export enum IntentType {

  UNKNOWN = 'UNKNOWN',

  GREETING = 'GREETING',

  THANKS = 'THANKS',

  GOODBYE = 'GOODBYE',

  SEARCH_PART = 'SEARCH_PART',

  HUMAN_TRANSFER = 'HUMAN_TRANSFER',

  CHEAPEST_RESULT = 'CHEAPEST_RESULT',

  MOST_EXPENSIVE_RESULT = 'MOST_EXPENSIVE_RESULT',

}
