export enum IntentType {

  UNKNOWN = 'UNKNOWN',

  GREETING = 'GREETING',

  THANKS = 'THANKS',

  GOODBYE = 'GOODBYE',

  SEARCH_PART = 'SEARCH_PART',

  HUMAN_TRANSFER = 'HUMAN_TRANSFER',

  CHEAPEST_RESULT = 'CHEAPEST_RESULT',

  MOST_EXPENSIVE_RESULT = 'MOST_EXPENSIVE_RESULT',

  CHECK_STOCK = 'CHECK_STOCK',

  VISIT_STORE = 'VISIT_STORE',

  CREATE_QUOTE = 'CREATE_QUOTE',

  ADD_QUOTE_ITEM = 'ADD_QUOTE_ITEM',

  QUOTE_SUMMARY = 'QUOTE_SUMMARY',

  REMOVE_QUOTE_ITEM = 'REMOVE_QUOTE_ITEM',

  MODIFY_QUOTE_QUANTITY = 'MODIFY_QUOTE_QUANTITY',

  CONFIRM_QUOTE = 'CONFIRM_QUOTE',

  CONFIRM_STOCK_QUANTITY = 'CONFIRM_STOCK_QUANTITY',

  CANCEL_STOCK_CONFIRMATION = 'CANCEL_STOCK_CONFIRMATION',
}
